// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://meaewizjldworjrnqzbz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1lYWV3aXpqbGR3b3Jqcm5xemJ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4MDU0NjksImV4cCI6MjA3MjM4MTQ2OX0.E4AEpsZi980DBY5za5eLoDXcZgVrkWn9qXMt6FDpjf8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});